// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sig.proto

package ftl_mixadp

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VerifyReq struct {
	SrcWlNamespace       string   `protobuf:"bytes,1,opt,name=src_wl_namespace,json=srcWlNamespace,proto3" json:"src_wl_namespace,omitempty"`
	SrcWlName            string   `protobuf:"bytes,2,opt,name=src_wl_name,json=srcWlName,proto3" json:"src_wl_name,omitempty"`
	DstWlNamespace       string   `protobuf:"bytes,101,opt,name=dst_wl_namespace,json=dstWlNamespace,proto3" json:"dst_wl_namespace,omitempty"`
	DstWlName            string   `protobuf:"bytes,102,opt,name=dst_wl_name,json=dstWlName,proto3" json:"dst_wl_name,omitempty"`
	DstSvcNamespace      string   `protobuf:"bytes,103,opt,name=dst_svc_namespace,json=dstSvcNamespace,proto3" json:"dst_svc_namespace,omitempty"`
	DstSvcName           string   `protobuf:"bytes,104,opt,name=dst_svc_name,json=dstSvcName,proto3" json:"dst_svc_name,omitempty"`
	DstPath              string   `protobuf:"bytes,105,opt,name=dst_path,json=dstPath,proto3" json:"dst_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyReq) Reset()         { *m = VerifyReq{} }
func (m *VerifyReq) String() string { return proto.CompactTextString(m) }
func (*VerifyReq) ProtoMessage()    {}
func (*VerifyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c066fc0129d1698, []int{0}
}

func (m *VerifyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyReq.Unmarshal(m, b)
}
func (m *VerifyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyReq.Marshal(b, m, deterministic)
}
func (m *VerifyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyReq.Merge(m, src)
}
func (m *VerifyReq) XXX_Size() int {
	return xxx_messageInfo_VerifyReq.Size(m)
}
func (m *VerifyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyReq.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyReq proto.InternalMessageInfo

func (m *VerifyReq) GetSrcWlNamespace() string {
	if m != nil {
		return m.SrcWlNamespace
	}
	return ""
}

func (m *VerifyReq) GetSrcWlName() string {
	if m != nil {
		return m.SrcWlName
	}
	return ""
}

func (m *VerifyReq) GetDstWlNamespace() string {
	if m != nil {
		return m.DstWlNamespace
	}
	return ""
}

func (m *VerifyReq) GetDstWlName() string {
	if m != nil {
		return m.DstWlName
	}
	return ""
}

func (m *VerifyReq) GetDstSvcNamespace() string {
	if m != nil {
		return m.DstSvcNamespace
	}
	return ""
}

func (m *VerifyReq) GetDstSvcName() string {
	if m != nil {
		return m.DstSvcName
	}
	return ""
}

func (m *VerifyReq) GetDstPath() string {
	if m != nil {
		return m.DstPath
	}
	return ""
}

type VerifyRsp struct {
	ErrCode string `protobuf:"bytes,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	// 下面列出的错误码：
	//    "sig_err": 票据验证不通过
	//    "no-sig": 没有发现有效票据
	ErrMsg               string   `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyRsp) Reset()         { *m = VerifyRsp{} }
func (m *VerifyRsp) String() string { return proto.CompactTextString(m) }
func (*VerifyRsp) ProtoMessage()    {}
func (*VerifyRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c066fc0129d1698, []int{1}
}

func (m *VerifyRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyRsp.Unmarshal(m, b)
}
func (m *VerifyRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyRsp.Marshal(b, m, deterministic)
}
func (m *VerifyRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyRsp.Merge(m, src)
}
func (m *VerifyRsp) XXX_Size() int {
	return xxx_messageInfo_VerifyRsp.Size(m)
}
func (m *VerifyRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyRsp.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyRsp proto.InternalMessageInfo

func (m *VerifyRsp) GetErrCode() string {
	if m != nil {
		return m.ErrCode
	}
	return ""
}

func (m *VerifyRsp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*VerifyReq)(nil), "ftl_mixadp.VerifyReq")
	proto.RegisterType((*VerifyRsp)(nil), "ftl_mixadp.VerifyRsp")
}

func init() { proto.RegisterFile("sig.proto", fileDescriptor_2c066fc0129d1698) }

var fileDescriptor_2c066fc0129d1698 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0xd1, 0xcf, 0x4a, 0xec, 0x30,
	0x14, 0xc7, 0x71, 0x66, 0x2e, 0x74, 0x6e, 0x8f, 0xe2, 0x9f, 0x80, 0x18, 0x5d, 0xc8, 0x30, 0xab,
	0xc1, 0x45, 0x17, 0x0a, 0xee, 0xc4, 0x85, 0x6b, 0x45, 0x66, 0x40, 0x97, 0x21, 0x26, 0x69, 0x1a,
	0x68, 0x6d, 0x3c, 0x27, 0x8c, 0xfa, 0x06, 0x3e, 0xb6, 0x24, 0x75, 0xda, 0x2a, 0xee, 0x4a, 0xf2,
	0xe1, 0x0b, 0xfd, 0x05, 0x72, 0x72, 0xb6, 0xf0, 0xd8, 0x86, 0x96, 0x41, 0x19, 0x6a, 0xd1, 0xb8,
	0x77, 0xa9, 0xfd, 0xe2, 0x73, 0x0a, 0xf9, 0xa3, 0x41, 0x57, 0x7e, 0xac, 0xcc, 0x2b, 0x5b, 0xc2,
	0x01, 0xa1, 0x12, 0x6f, 0xb5, 0x78, 0x91, 0x8d, 0x21, 0x2f, 0x95, 0xe1, 0x93, 0xf9, 0x64, 0x99,
	0xaf, 0xf6, 0x08, 0xd5, 0x53, 0x7d, 0xbf, 0x3d, 0x65, 0x67, 0xb0, 0x33, 0x92, 0x7c, 0x9a, 0x50,
	0xde, 0xa3, 0x58, 0xd2, 0x14, 0x7e, 0x96, 0x4c, 0x57, 0xd2, 0x14, 0x7e, 0x95, 0x46, 0x92, 0x97,
	0x5d, 0xa9, 0x47, 0xec, 0x1c, 0x0e, 0xe3, 0x3d, 0x6d, 0xd4, 0x28, 0x65, 0x93, 0xda, 0xd7, 0x14,
	0xd6, 0x1b, 0x35, 0xb4, 0xe6, 0xb0, 0x3b, 0xb6, 0xbc, 0x4a, 0x0c, 0x06, 0xc6, 0x4e, 0xe0, 0x7f,
	0x14, 0x5e, 0x86, 0x8a, 0xbb, 0x74, 0x3b, 0xd3, 0x14, 0x1e, 0x64, 0xa8, 0x16, 0x37, 0xfd, 0x12,
	0xe4, 0xa3, 0x33, 0x88, 0x42, 0xb5, 0x7a, 0xbb, 0xc0, 0xcc, 0x20, 0xde, 0xb6, 0xda, 0xb0, 0x63,
	0x88, 0x9f, 0xa2, 0x21, 0xfb, 0xfd, 0xdb, 0x99, 0x41, 0xbc, 0x23, 0x7b, 0x71, 0x0d, 0xff, 0xd6,
	0xce, 0xb2, 0x2b, 0xc8, 0xba, 0x0e, 0x3b, 0x2a, 0x86, 0xa5, 0x8b, 0x7e, 0xe5, 0xd3, 0xbf, 0x8e,
	0xc9, 0x3f, 0x67, 0xe9, 0x75, 0x2e, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x0d, 0xd3, 0x32, 0x1e,
	0xaa, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SigClient is the client API for Sig service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SigClient interface {
	// 验票
	//注意：需要Mixer把收到的请求的metadata放在这个验票请求里，票据都在metadata里。
	Verify(ctx context.Context, in *VerifyReq, opts ...grpc.CallOption) (*VerifyRsp, error)
}

type sigClient struct {
	cc *grpc.ClientConn
}

func NewSigClient(cc *grpc.ClientConn) SigClient {
	return &sigClient{cc}
}

func (c *sigClient) Verify(ctx context.Context, in *VerifyReq, opts ...grpc.CallOption) (*VerifyRsp, error) {
	out := new(VerifyRsp)
	err := c.cc.Invoke(ctx, "/ftl_mixadp.Sig/Verify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SigServer is the server API for Sig service.
type SigServer interface {
	// 验票
	//注意：需要Mixer把收到的请求的metadata放在这个验票请求里，票据都在metadata里。
	Verify(context.Context, *VerifyReq) (*VerifyRsp, error)
}

// UnimplementedSigServer can be embedded to have forward compatible implementations.
type UnimplementedSigServer struct {
}

func (*UnimplementedSigServer) Verify(ctx context.Context, req *VerifyReq) (*VerifyRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}

func RegisterSigServer(s *grpc.Server, srv SigServer) {
	s.RegisterService(&_Sig_serviceDesc, srv)
}

func _Sig_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ftl_mixadp.Sig/Verify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigServer).Verify(ctx, req.(*VerifyReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sig_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ftl_mixadp.Sig",
	HandlerType: (*SigServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Verify",
			Handler:    _Sig_Verify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sig.proto",
}
